version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENCODING: UTF-8
      POSTGRES_DB: store
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  pgdata:
